# Numpy e Arrays
---

- Numpy é ideal para o processamento de dados numericos;
- Mais próximos do hardware, ou seja, mais eficiência;
- Pacotes adicionais ao Python para Arrays multidimensionais;

In [ ]:
import numpy as np

In [6]:
#primeira forma de implementação
array = np.array([1, 2, 3, 4, 5]) #Gera um array

In [7]:
print(array)
print(type(array))
array

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

## Criação Automática de Arrays
---

### 1. arange

In [10]:
#Segunda forma
np.arange(10)
# O arange é como o range() tradicional que gera uma lista automática

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 10, 12)
#           inicio, fim, numeros entre os dois

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [16]:
#Endpoint pode ser usado para decidir se quer contar o ultimo número ou não
np.linspace(0, 10, 12, endpoint=False)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        , 5.83333333, 6.66666667, 7.5       ,
       8.33333333, 9.16666667])

# Funções para criar arrays comuns
---

In [18]:
np.zeros(10) #Cria um array de zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10) # Cria array de um

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.random.randint(1, 10, 10) #Cria um array de números aleatórios
#                 inicio, fim, tamanho do array

array([5, 8, 9, 3, 1, 7, 1, 3, 2, 9])

In [78]:
np.random.randn(10)

array([ 0.12802766, -0.47468371, -0.29010261, -1.65738752, -0.15942396,
        0.14437303,  0.58921743,  0.78896132,  0.03689692, -0.53821327])

In [54]:
np.random.choice([1, 2, 3, 4, 5]) #Escolhe um número aleatório entre o iterável

1

In [53]:
array = np.array([1, 2, 3, 4, 5])

In [48]:
array.ndim # Mostra quantas dimensões possui

1

In [55]:
array.shape

(5,)

In [61]:
array.dtype

dtype('int32')

In [63]:
array.min()

1

# Matriz
---

In [65]:
matriz = np.array([[1,2,3], [1, 2, 3], [1, 2, 3]])

In [68]:
matriz.ndim

2

In [70]:
matriz.shape #Formato da matriz, 3*3 -> 3 linhas e 3 colunas

(3, 3)

# Criando Matrizes Comuns
---

In [73]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [82]:
np.random.rand(3, 3)

array([[0.8972439 , 0.82507191, 0.75906125],
       [0.02120045, 0.14678879, 0.34948933],
       [0.49075378, 0.0482411 , 0.55526973]])

In [83]:
np.random.randint(1, 100, (5, 5))

array([[59, 40, 86, 16, 77],
       [65, 54, 67, 91, 14],
       [31, 45,  3, 39, 13],
       [32, 40, 92, 75, 74],
       [76, 86, 35, 87, 40]])

# Outro Métodos Importantes
---

In [87]:
np.min(array)

1

In [89]:
np.max(array)

5

In [94]:
np.sum(array)

15

In [96]:
np.argmin(array) #Traz o índice do menor elemento

0

In [98]:
np.argmax(array) #Traz o índice do maior elemento

4

In [101]:
np.mean(array) #Faz a média

3.0

In [104]:
np.var(array) #Calcula a variância

2.0

In [107]:
np.std(array) # Calcula desvio padrão

1.4142135623730951

In [109]:
np.sort(array) # Ordena array

array([1, 2, 3, 4, 5])

In [117]:
array.astype(np.float32) # Modificar o tipo do array

array([1., 2., 3., 4., 5.], dtype=float32)

In [120]:
array2 = np.arange(16)

In [123]:
len(array2)

16

In [132]:
matriz = array2.reshape((4, 4)) #Faz um novo shape

In [157]:
matriz[1][3]

# ou

matriz[1, 3]

7

In [158]:
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
matriz[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

# Operações envolvendo Arrays
---

### Operações com números

In [173]:
np.ones(5) + 5 #Soma a cada elementos

array([6., 6., 6., 6., 6.])

In [175]:
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [179]:
np.ones(5) - 5

array([-4., -4., -4., -4., -4.])

In [181]:
np.ones(5) / 5

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [ ]:
np.ones(5) ** 5

In [186]:
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
matriz / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

### Operações entre Arrays

In [188]:
array

array([1, 2, 3, 4, 5])

In [187]:
array + array # Soma elemento a elemento

array([ 2,  4,  6,  8, 10])

In [190]:
array + np.arange(3)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [196]:
array3 = np.random.randint(10, size=(5,2))
array4 = np.random.randint(10, size=(2,4))

In [198]:
#Multiplicação matemática de matrizes

array3.dot(array4)

array([[ 42,  18, 114,  51],
       [  8,   0,  32,  20],
       [ 26,  18,  50,  11],
       [ 12,   0,  48,  30],
       [ 36,  27,  63,   9]])

### Funções matemáticas
---

In [200]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [202]:
array

array([1, 2, 3, 4, 5])

In [205]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [211]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [209]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])