### Grafos
---

### Tipos de grafos

1. Grafo Dirigido
2. Grafo não Dirigido

### 1.Matriz de Adjacência

In [1]:
import numpy as np

In [53]:
class Grafo:
    def __init__(self, N):
        self.N = N
        #representação da Matriz
        self.adj = np.zeros((N, N))
    def __repr__(self):
        return str(self.adj)
    def add_arrow(self, n1, n2, weight=1):
        self.adj[n1, n2] = weight
    def add_edge(self, n1, n2, weigth=1):
        self.add_arrow(n1, n2, weigth)
        self.add_arrow(n2, n1, weigth)    
    def get_neighbirs(self, n):
        return [i for i, v in enumerate(self.adj[n]) if v]

In [54]:
grafo = Grafo(7)

In [55]:
grafo.add_edge(0, 1)
grafo.add_edge(0, 2)
grafo.add_edge(1, 2)
grafo.add_edge(1, 3)
grafo.add_edge(2, 4)
grafo.add_edge(3, 4)
grafo.add_edge(4, 5)
grafo.add_edge(5, 6)

In [56]:
grafo

[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]]

In [57]:
grafo.get_neighbirs(0)

[1, 2]

### 2. Lista de Adjacências

In [107]:
class GrafoLista:
    def __init__(self, N):
        self.N = N
        self.adj = [[] for _ in range(N)]
    def __repr__(self):
        l = [str(line) for line in self.adj]
        return '\n'.join(l)

    def add_arrow(self, n1, n2):
        if n2 not in self.adj[n1]:
            self.adj[n1].append(n2)
        else:
            return 'Valores já estão conectados'
    def add_edge(self, n1, n2):
        self.add_arrow(n1, n2)
        self.add_arrow(n2, n1)
    
    def get_neighbors(self, n):
        return self.adj[n]

In [108]:
grafo = GrafoLista(4)

In [109]:
grafo.add_arrow(0, 1)
grafo.add_arrow(0, 2)
grafo.add_arrow(1, 2)
grafo.add_arrow(3, 0)

In [111]:
grafo

[1, 2]
[2]
[]
[0]

In [113]:
grafo.get_neighbors(0)

[1, 2]

# DFS - Busca por profundidade

In [3]:
class Grafo:
    def __init__(self, N):
        self.N = N
        self.adj = [[] for _ in range(N)]
    def __repr__(self):
        l = [str(line) for line in self.adj]
        return '\n'.join(l)

    def add_arrow(self, n1, n2):
        if n2 not in self.adj[n1]:
            self.adj[n1].append(n2)
        else:
            return 'Valores já estão conectados'
    def add_edge(self, n1, n2):
        self.add_arrow(n1, n2)
        self.add_arrow(n2, n1)
        
    def DFS(self, no_inicio, vistados):
        visitados[no_inicio] = True
        
        print('Visitando o nó {}'.format(no_inicio))
        
        for adjacente in self.adj[no_inicio]:
            print(adjacente)
            if not visitados[adjacente]:
                self.DFS(adjacente, visitados)

In [4]:
grafo = Grafo(4)

In [5]:
grafo.add_edge(0, 1)
grafo.add_edge(0, 2)
grafo.add_edge(1, 2)
grafo.add_edge(3, 0)

In [6]:
visitados = [False for i in range(grafo.N)]
visitados

[False, False, False, False]

In [7]:
grafo.DFS(0, visitados)

Visitando o nó 0
1
Visitando o nó 1
0
2
Visitando o nó 2
0
1
2
3
Visitando o nó 3
0
